# Use Node LTS base
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm ci

# Copy the rest
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose the port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]




dubai wale ka app submit krna h 
cneox ka deploy krna h 
with testing and everything
fusetrix ko app store per live krna h along with lodgezify 



http://localhost:3000/signup?referrer=CROWN-000002&position=left



http://localhost:3000/signup?referrer=CROWN-000002&position=right





so this binary calucaltion should work on  at the end of the day on cron job  just like roi not immedieatly.



and only referal bonus should work immediealt 